document.getElementById('btn5').addEventListener('click',function(){
Module.ccall("lck");
});
document.getElementById('btn4').addEventListener('click',function(){
Module.ccall("swtch");
});
document.getElementById('btn').addEventListener('click',function(){
Module.ccall('chng');
});
document.getElementById('btn7').addEventListener('click',function(){
document.getElementById("canvas").style="position:absolute;background-color:rgba(1,1,1,0);z-index:999995;image-rendering:pixelated;width:2048px;height:2048px;";
Module.ccall('rst');
});
