#!/usr/bin/env node
// Build html/featured_pack_manifest.json — curated 30–50 showcase presets.
//
// Combines Signature Series + verified custom presets with light-tier picks
// from weeks_presets/ (audit report). Run after generate_custom_preset_manifest.mjs.
//
// Usage: node scripts/build_featured_pack.mjs [--check] [--max N]

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { computeQualityWeight } from './preset_metadata.mjs';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const customManifestPath = join(repoRoot, 'html', 'custom_presets_manifest.json');
const auditPath = join(repoRoot, 'docs', 'preset_audit_report.json');
const outPath = join(repoRoot, 'html', 'featured_pack_manifest.json');

const maxArg = process.argv.find((a) => a.startsWith('--max='));
const TARGET_MAX = maxArg ? Number(maxArg.split('=')[1]) : 45;
const TARGET_MIN = 30;

function scoreWeeksEntry(r) {
    let score = 0;
    if (r.tier === 'light') score += 10;
    else if (r.tier === 'medium') score += 4;
    if (r.reactive) score += 6;
    if (r.ok) score += 3;
    const cost = r.metrics?.cost ?? 99;
    score += Math.max(0, 20 - cost);
    return score;
}

function buildPack() {
    if (!existsSync(customManifestPath)) {
        throw new Error(`Missing ${customManifestPath} — run generate_custom_preset_manifest.mjs first`);
    }
    const custom = JSON.parse(readFileSync(customManifestPath, 'utf8'));
    const selected = new Map();

    const add = (entry) => {
        const key = `${entry.base || 'custom_milk_fixed'}::${entry.file}`;
        if (!selected.has(key) && entry.status !== 'broken') {
            selected.set(key, { ...entry, weight: computeQualityWeight(entry) });
        }
    };

    // 1. Signature / featured custom presets
    for (const p of custom.presets || []) {
        if (p.featured || p.tags?.includes('signature')) add(p);
    }

    // 2. Verified ok custom presets
    for (const p of custom.presets || []) {
        if (p.status === 'ok') add(p);
    }

    // 3. Remaining non-broken custom (unknown status)
    for (const p of custom.presets || []) {
        if (p.status !== 'broken') add(p);
    }

    // 4. Light reactive weeks_presets, then medium if still under target
    if (existsSync(auditPath)) {
        const audit = JSON.parse(readFileSync(auditPath, 'utf8'));
        const weeks = (audit.corpora || []).find((c) => c.dir === 'weeks_presets');
        const allWeeks = (weeks?.results || []).filter((r) => r.ok);

        const tierPasses = ['light', 'medium'];
        for (const tier of tierPasses) {
            const candidates = allWeeks
                .filter((r) => r.tier === tier)
                .sort((a, b) => scoreWeeksEntry(b) - scoreWeeksEntry(a));

            for (const r of candidates) {
                if (selected.size >= TARGET_MAX) break;
                add({
                    file: r.name,
                    base: 'weeks_presets',
                    label: (r.description || r.name).replace(/\.milk$/i, '').slice(0, 64),
                    status: 'unknown',
                    meanRgb: null,
                    tags: r.reactive ? ['reactive', 'classic'] : ['classic'],
                    tier: r.tier,
                    reactivity: r.reactive ? 'high' : 'none',
                    author: r.author || null,
                    version: r.version || null,
                    project: null,
                    featured: false,
                });
            }
            if (selected.size >= TARGET_MIN) break;
        }
    }

    let presets = [...selected.values()].map((p) => ({ ...p, featured: true }));
    if (presets.length > TARGET_MAX) {
        presets = presets
            .sort((a, b) => (b.weight ?? 0) - (a.weight ?? 0))
            .slice(0, TARGET_MAX);
    }

    return {
        $comment: 'AUTO-GENERATED by scripts/build_featured_pack.mjs — curated showcase pack for B3HD.',
        schemaVersion: 2,
        generatedAt: new Date().toISOString().slice(0, 10),
        packName: 'Featured / Signature',
        targetSize: { min: TARGET_MIN, max: TARGET_MAX },
        sources: ['custom_milk_fixed', 'weeks_presets'],
        presets,
    };
}

const manifest = buildPack();
const serialized = `${JSON.stringify(manifest, null, 2)}\n`;

if (process.argv.includes('--check')) {
    const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
    const normalize = (s) => s.replace(/"generatedAt":\s*"[^"]*"/, '"generatedAt":"_"');
    if (normalize(current) !== normalize(serialized)) {
        console.error(`Stale featured pack: ${outPath}. Run: node scripts/build_featured_pack.mjs`);
        process.exit(1);
    }
    console.log('Featured pack manifest is up to date.');
    process.exit(0);
}

writeFileSync(outPath, serialized);
console.log(`Wrote ${outPath} (${manifest.presets.length} presets).`);
