# wasm_link_common.inc.sh
# AUTO-GENERATED by cmake/GenerateWasmLinkCommon.cmake — do not edit by hand.
# Canonical definitions live in cmake/EmscriptenWasmFlags.cmake.
# Regenerate: scripts/sync_wasm_link_common.sh
#
# Source from build_wasm_smoke_wrapper.sh, build_projectm.sh, colab_build.sh:
#   source "$(dirname "${BASH_SOURCE[0]}")/wasm_link_common.inc.sh"

# shellcheck disable=SC2034  # consumed by sourcing scripts
PROJECTM_WASM_EXPORTED_FUNCTIONS=(
    _malloc
    _free
    _main
    _add_audio_data
    _pl
    _destruct
    _get_projectm_handle
    _init
    _set_canvas_selectors
    _init_with_canvases
    _rebind_canvases
    _load_preset_file
    _switch_preset
    _set_aspect_correction
    _render_frame
    _start_render
    _set_window_size
    _set_mesh
    _add_preset_path
    _add_existing_vfs_presets
    _add_preset_file
    _add_custom_milk_paths
    _projectm_pcm_add_float_wrapper
    _create_sprite
    _stop_worklet_playback
    _set_audio_source_to_stream
    _set_preset_locked
    _set_transparency_mode
    _get_transparency_mode
    _set_transparency_threshold
    _get_transparency_threshold
    _set_perf_hud
    _set_target_fps
    _set_quality_governor
    _get_quality_tier
    _get_governor_render_scale
    _get_governor_blur_cap
    _is_preset_ready
    _get_rendered_frame_count
    _preset_switch_failed
    _get_omp_enabled
    _get_omp_max_threads
    _get_omp_thread_count_in_parallel
    _get_omp_blocktime
    _shader_cache_begin_load
    _shader_cache_import_glsl
    _shader_cache_end_load
    _get_glsl_generator_version
    _pm_handle_context_loss
    _dual_fbo_begin_transition
    _dual_fbo_end_transition
    _dual_fbo_cancel_transition
    _dual_fbo_swap_preset_a
    _dual_fbo_swap_preset_b
    _dual_fbo_get_a_read_fbo
    _dual_fbo_get_a_write_fbo
    _dual_fbo_get_a_read_tex
    _dual_fbo_get_a_write_tex
    _dual_fbo_get_b_read_fbo
    _dual_fbo_get_b_write_fbo
    _dual_fbo_get_b_read_tex
    _dual_fbo_get_b_write_tex
    _dual_fbo_is_preset_a_allocated
    _dual_fbo_is_preset_b_allocated
    _dual_fbo_set_idle_release_seconds
    _dual_fbo_get_idle_release_seconds
    _dual_fbo_is_preset_b_ready
    _dual_fbo_get_format
    _dual_fbo_render_preset_a
    _dual_fbo_render_preset_b
    _transition_start
    _transition_cancel
    _transition_is_active
    _transition_get_blend
    _transition_set_duration
    _transition_get_duration
)

projectm_wasm_join_exported_functions() {
    local IFS=,
    echo "${PROJECTM_WASM_EXPORTED_FUNCTIONS[*]}"
}

# EXPORTED_RUNTIME_METHODS for the final wrapper link (common + VFS FS helper).
projectm_wasm_exported_runtime_methods() {
    echo "ccall,cwrap,FS"
}

# SIMD + atomics compile flags for the final emcc link of projectM_emscripten.cpp.
# Must stay in sync with projectm_apply_emscripten_lib_compile_flags() in
# cmake/EmscriptenWasmFlags.cmake so the wrapper TU and prebuilt libprojectM-4.a
# agree on wasm32 feature levels.
projectm_wasm_simd_compile_args() {
    local -n _out=$1
    _out=(
        -msimd128
        -mrelaxed-simd
        -mmutable-globals
        -mbulk-memory
        -matomics
        -mnontrapping-fptoint
        -msign-ext
        -fno-strict-aliasing
        -fno-math-errno
    )
}

# Optional env overrides:
#   PROJECTM_WASM_LTO=1              add -flto to the final wrapper link (link-time only)
#   PROJECTM_WASM_PTHREAD_POOL_SIZE  pre-spawned pthread Workers (default 4)
#   ENABLE_WASM_TRANSITIONS=ON       (default) adds ASYNCIFY_STACK_SIZE
# ASYNCIFY_ONLY always points at cmake/wasm_asyncify_only.txt (absolute path required).
projectm_wasm_pthread_pool_size() {
    echo "${PROJECTM_WASM_PTHREAD_POOL_SIZE:-4}"
}

projectm_wasm_asyncify_only_file() {
    # When this .inc.sh is sourced, BASH_SOURCE[0] is scripts/wasm_link_common.inc.sh.
    local _root
    _root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    echo "${_root}/cmake/wasm_asyncify_only.txt"
}

projectm_wasm_common_link_args() {
    local -n _out=$1
    local pthread_pool_size
    pthread_pool_size="$(projectm_wasm_pthread_pool_size)"
    local asyncify_only_file
    asyncify_only_file="$(projectm_wasm_asyncify_only_file)"
    local transition_args=()
    if [[ "${ENABLE_WASM_TRANSITIONS:-ON}" == "ON" ]]; then
        transition_args+=("-s" "ASYNCIFY_STACK_SIZE=65536")
    fi

    local lto_args=()
    if [[ "${PROJECTM_WASM_LTO:-0}" == "1" ]]; then
        lto_args+=("-flto")
    fi

    _out=(
        "${lto_args[@]}"
        -std=c++20
        -O3
        -rtlib=compiler-rt-mt
        -mtune=wasm32
        -pthread
        -fopenmp=libomp
        -fno-math-errno
        -s SHARED_MEMORY=1
        -s WASM_WORKERS=1
        -s MIN_WEBGL_VERSION=2
        -s MAX_WEBGL_VERSION=2
        -s USE_WEBGL2=1
        -s FULL_ES2=0
        -s FULL_ES3=1
        -s GL_POOL_TEMP_BUFFERS=0
        -s GL_MAX_TEMP_BUFFER_SIZE=33177600
        -s GL_TRACK_ERRORS=0
        -s NO_DISABLE_EXCEPTION_CATCHING=1
        -s ALLOW_MEMORY_GROWTH=1
        -s MALLOC=mimalloc
        -s MAXIMUM_MEMORY=4gb
        -s INITIAL_MEMORY=256mb
        -s FORCE_FILESYSTEM=1
        -s ASYNCIFY=1
        -s "PTHREAD_POOL_SIZE=${pthread_pool_size}"
        -s ENVIRONMENT=web,worker
        -s EXPORT_NAME=createModule
        -s MODULARIZE=1
        -s DEFAULT_TO_CXX=1
        -l embind
        -s EXPORTED_FUNCTIONS="$(projectm_wasm_join_exported_functions)"
        -s EXPORTED_RUNTIME_METHODS="$(projectm_wasm_exported_runtime_methods)"
        -s "ASYNCIFY_ONLY=@${asyncify_only_file}"
        "${transition_args[@]}"
    )
}

projectm_wasm_libomp_args() {
    local root="${1:-}"
    if [[ -f "$root/libomp.a" ]]; then
        echo "$root/libomp.a"
    elif [[ -f "$root/omp/libomp.a" ]]; then
        echo "$root/omp/libomp.a"
    fi
}
