# Generate scripts/wasm_link_common.inc.sh from cmake/EmscriptenWasmFlags.cmake.
#
# Usage:
#   cmake -P cmake/GenerateWasmLinkCommon.cmake
#   scripts/sync_wasm_link_common.sh

cmake_minimum_required(VERSION 3.21)

get_filename_component(PROJECTM_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/EmscriptenWasmFlags.cmake")

set(_out "${PROJECTM_SOURCE_DIR}/scripts/wasm_link_common.inc.sh")

set(_exported_function_lines "")
foreach(_fn IN LISTS PROJECTM_WASM_WRAPPER_EXPORTED_FUNCTIONS)
    string(APPEND _exported_function_lines "    ${_fn}\n")
endforeach()

file(WRITE "${_out}" "# wasm_link_common.inc.sh
# AUTO-GENERATED by cmake/GenerateWasmLinkCommon.cmake — do not edit by hand.
# Canonical definitions live in cmake/EmscriptenWasmFlags.cmake.
# Regenerate: scripts/sync_wasm_link_common.sh
#
# Source from build_wasm_smoke_wrapper.sh, build_projectm.sh, colab_build.sh:
#   source \"\$(dirname \"\${BASH_SOURCE[0]}\")/wasm_link_common.inc.sh\"

# shellcheck disable=SC2034  # consumed by sourcing scripts
PROJECTM_WASM_EXPORTED_FUNCTIONS=(
${_exported_function_lines})

projectm_wasm_join_exported_functions() {
    local IFS=,
    echo \"\${PROJECTM_WASM_EXPORTED_FUNCTIONS[*]}\"
}

# SIMD + atomics compile flags for the final emcc link of projectM_emscripten.cpp.
# Must stay in sync with projectm_apply_emscripten_lib_compile_flags() in
# cmake/EmscriptenWasmFlags.cmake so the wrapper TU and prebuilt libprojectM-4.a
# agree on wasm32 feature levels.
projectm_wasm_simd_compile_args() {
    local -n _out=\$1
    _out=(
")

foreach(_flag IN LISTS PROJECTM_WASM_SIMD_COMPILE_FLAGS)
    file(APPEND "${_out}" "        ${_flag}\n")
endforeach()

file(APPEND "${_out}" "    )
}

# Common emcc arguments (array). Caller may append lib paths and -o.
# Optional env overrides:
#   PROJECTM_WASM_LTO=1              add -flto to the final wrapper link (link-time only)
#   PROJECTM_WASM_PTHREAD_POOL_SIZE  pre-spawned pthread Workers (default ${PROJECTM_WASM_PTHREAD_POOL_SIZE})
#   ENABLE_WASM_TRANSITIONS=ON       (default) adds ASYNCIFY_STACK_SIZE
projectm_wasm_pthread_pool_size() {
    echo \"\${PROJECTM_WASM_PTHREAD_POOL_SIZE:-${PROJECTM_WASM_PTHREAD_POOL_SIZE}}\"
}

projectm_wasm_common_link_args() {
    local -n _out=\$1
    local pthread_pool_size
    pthread_pool_size=\"\$(projectm_wasm_pthread_pool_size)\"
    local transition_args=()
    if [[ \"\${ENABLE_WASM_TRANSITIONS:-ON}\" == \"ON\" ]]; then
        transition_args+=(\"-s\" \"ASYNCIFY_STACK_SIZE=65536\")
    fi

    local lto_args=()
    if [[ \"\${PROJECTM_WASM_LTO:-0}\" == \"1\" ]]; then
        lto_args+=(\"-flto\")
    fi

    local simd_args=()
    projectm_wasm_simd_compile_args simd_args

    _out=(
        -O3
        \"\${lto_args[@]}\"
        \"\${simd_args[@]}\"
        -l embind
        -pthread
        -fopenmp=libomp
        -s ALLOW_MEMORY_GROWTH=1
        -s NO_DISABLE_EXCEPTION_CATCHING=1
        -s ENVIRONMENT=web,worker
        -s SHARED_MEMORY=1
        -s EXPORTED_FUNCTIONS=\"\$(projectm_wasm_join_exported_functions)\"
        -s EXPORTED_RUNTIME_METHODS=ccall,FS
        -s EXPORT_NAME=createModule
        -s \"PTHREAD_POOL_SIZE=\${pthread_pool_size}\"
        -s FULL_ES2=0
        -s FULL_ES3=1
        -s MIN_WEBGL_VERSION=2
        -s MAX_WEBGL_VERSION=2
        -s MODULARIZE=1
        -s ASYNCIFY=1
        \"\${transition_args[@]}\"
        -s FORCE_FILESYSTEM=1
    )
}

projectm_wasm_libomp_args() {
    local root=\"\${1:-}\"
    if [[ -f \"\$root/libomp.a\" ]]; then
        echo \"\$root/libomp.a\"
    elif [[ -f \"\$root/omp/libomp.a\" ]]; then
        echo \"\$root/omp/libomp.a\"
    fi
}
")

message(STATUS "Wrote ${_out}")
