# Generate scripts/wasm_link_common.inc.sh and cmake/generated/ProjectMWasmBuildConfig.hpp
# from cmake/EmscriptenWasmFlags.cmake.
#
# Usage:
#   cmake -P cmake/GenerateWasmLinkCommon.cmake
#   scripts/sync_wasm_link_common.sh

cmake_minimum_required(VERSION 3.21)

get_filename_component(PROJECTM_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/EmscriptenWasmFlags.cmake")

set(_inc_out "${PROJECTM_SOURCE_DIR}/scripts/wasm_link_common.inc.sh")
set(_header_out "${PROJECTM_SOURCE_DIR}/cmake/generated/ProjectMWasmBuildConfig.hpp")

file(MAKE_DIRECTORY "${PROJECTM_SOURCE_DIR}/cmake/generated")

function(_projectm_wasm_shell_quote value out_var)
    string(REPLACE "\\" "\\\\" _escaped "${value}")
    string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
    set(${out_var} "\"${_escaped}\"" PARENT_SCOPE)
endfunction()

function(_projectm_wasm_append_shell_s_settings settings_list out_lines_var)
    foreach(_setting IN LISTS ${settings_list})
        if(_setting MATCHES "^([^=]+)=(.*)$")
            list(APPEND ${out_lines_var} "        -s ${CMAKE_MATCH_1}=${CMAKE_MATCH_2}")
        else()
            list(APPEND ${out_lines_var} "        -s ${_setting}=1")
        endif()
    endforeach()
    set(${out_lines_var} "${${out_lines_var}}" PARENT_SCOPE)
endfunction()

set(_exported_function_lines "")
foreach(_fn IN LISTS PROJECTM_WASM_WRAPPER_EXPORTED_FUNCTIONS)
    string(APPEND _exported_function_lines "    ${_fn}\n")
endforeach()

set(_simd_flag_lines "")
foreach(_flag IN LISTS PROJECTM_WASM_SIMD_COMPILE_FLAGS)
    string(APPEND _simd_flag_lines "        ${_flag}\n")
endforeach()

set(_shared_plain_lines "")
foreach(_flag IN LISTS PROJECTM_WASM_SHARED_PLAIN_LINK_ARGS)
    string(APPEND _shared_plain_lines "        ${_flag}\n")
endforeach()

set(_shared_s_lines "")
_projectm_wasm_append_shell_s_settings(PROJECTM_WASM_SHARED_S_LINK_SETTINGS _shared_s_lines)

set(_wrapper_s_lines "")
_projectm_wasm_append_shell_s_settings(PROJECTM_WASM_WRAPPER_ONLY_S_LINK_SETTINGS _wrapper_s_lines)

set(_shared_s_block "")
foreach(_line IN LISTS _shared_s_lines)
    string(APPEND _shared_s_block "${_line}\n")
endforeach()

set(_wrapper_s_block "")
foreach(_line IN LISTS _wrapper_s_lines)
    string(APPEND _wrapper_s_block "${_line}\n")
endforeach()

file(WRITE "${_inc_out}" "# wasm_link_common.inc.sh
# AUTO-GENERATED by cmake/GenerateWasmLinkCommon.cmake — do not edit by hand.
# Canonical definitions live in cmake/EmscriptenWasmFlags.cmake.
# Regenerate: scripts/sync_wasm_link_common.sh
#
# Source from build_wasm_smoke_wrapper.sh, build_projectm.sh, colab_build.sh:
#   source \"\$(dirname \"\${BASH_SOURCE[0]}\")/wasm_link_common.inc.sh\"

# shellcheck disable=SC2034  # consumed by sourcing scripts
PROJECTM_WASM_EXPORTED_FUNCTIONS=(
${_exported_function_lines})

projectm_wasm_join_exported_functions() {
    local IFS=,
    echo \"\${PROJECTM_WASM_EXPORTED_FUNCTIONS[*]}\"
}

# EXPORTED_RUNTIME_METHODS for the final wrapper link (common + VFS FS helper).
projectm_wasm_exported_runtime_methods() {
    echo \"${PROJECTM_WASM_WRAPPER_EXPORTED_RUNTIME_METHODS_STR}\"
}

# SIMD + atomics compile flags for the final emcc link of projectM_emscripten.cpp.
# Must stay in sync with projectm_apply_emscripten_lib_compile_flags() in
# cmake/EmscriptenWasmFlags.cmake so the wrapper TU and prebuilt libprojectM-4.a
# agree on wasm32 feature levels.
projectm_wasm_simd_compile_args() {
    local -n _out=\$1
    _out=(
${_simd_flag_lines}    )
}

# Optional env overrides:
#   PROJECTM_WASM_LTO=1              add -flto to the final wrapper link (link-time only)
#   PROJECTM_WASM_PTHREAD_POOL_SIZE  pre-spawned pthread Workers (default ${PROJECTM_WASM_PTHREAD_POOL_SIZE})
#   ENABLE_WASM_TRANSITIONS=ON       (default) adds ASYNCIFY_STACK_SIZE
projectm_wasm_pthread_pool_size() {
    echo \"\${PROJECTM_WASM_PTHREAD_POOL_SIZE:-${PROJECTM_WASM_PTHREAD_POOL_SIZE}}\"
}

projectm_wasm_common_link_args() {
    local -n _out=\$1
    local pthread_pool_size
    pthread_pool_size=\"\$(projectm_wasm_pthread_pool_size)\"
    local transition_args=()
    if [[ \"\${ENABLE_WASM_TRANSITIONS:-ON}\" == \"ON\" ]]; then
        transition_args+=(\"-s\" \"ASYNCIFY_STACK_SIZE=65536\")
    fi

    local lto_args=()
    if [[ \"\${PROJECTM_WASM_LTO:-0}\" == \"1\" ]]; then
        lto_args+=(\"-flto\")
    fi

    _out=(
        \"\${lto_args[@]}\"
${_shared_plain_lines}${_shared_s_block}        -s \"PTHREAD_POOL_SIZE=\${pthread_pool_size}\"
${_wrapper_s_block}        -l embind
        -s EXPORTED_FUNCTIONS=\"\$(projectm_wasm_join_exported_functions)\"
        -s EXPORTED_RUNTIME_METHODS=\"\$(projectm_wasm_exported_runtime_methods)\"
        \"\${transition_args[@]}\"
    )
}

projectm_wasm_libomp_args() {
    local root=\"\${1:-}\"
    if [[ -f \"\$root/libomp.a\" ]]; then
        echo \"\$root/libomp.a\"
    elif [[ -f \"\$root/omp/libomp.a\" ]]; then
        echo \"\$root/omp/libomp.a\"
    fi
}
")

file(WRITE "${_header_out}" "// ProjectMWasmBuildConfig.hpp
// AUTO-GENERATED by cmake/GenerateWasmLinkCommon.cmake — do not edit by hand.
// Canonical value: PROJECTM_WASM_PTHREAD_POOL_SIZE in cmake/EmscriptenWasmFlags.cmake
// Regenerate: scripts/sync_wasm_link_common.sh

#pragma once

// Pre-spawned pthread Workers (PTHREAD_POOL_SIZE). OpenMP thread count in
// projectM_emscripten.cpp::ConfigureWasmOpenMPThreadCount() must match this.
constexpr int kWasmPthreadPoolSize = ${PROJECTM_WASM_PTHREAD_POOL_SIZE};
")

message(STATUS "Wrote ${_inc_out}")
message(STATUS "Wrote ${_header_out}")
