# WasmApiManifest.cmake
#
# WASM JavaScript API metadata: signatures, bindings, and visibility tiers.
# Included by cmake/EmscriptenWasmFlags.cmake; drives generation of
# html/generated/projectm-wasm-api.ts via cmake/GenerateWasmLinkCommon.cmake.
#
# Each entry: name|visibility|binding|returns|args|doc
#   visibility: public | internal | runtime
#   binding:    direct | ccall
#   returns:    void | number | boolean | string
#   args:       comma-separated name:type pairs (types: number, boolean, string, pointer)
#
# Names must match PROJECTM_WASM_WRAPPER_EXPORTED_FUNCTIONS (without leading _),
# except _malloc, _free, _main which are runtime-only.

set(PROJECTM_WASM_API_MANIFEST
    "malloc|runtime|direct|number|size:number|Allocate bytes on the WASM heap"
    "free|runtime|direct|void|ptr:number|Free a WASM heap allocation"
    "add_audio_data|internal|direct|void|data:pointer,len:number|Legacy uint8 PCM feed"
    "pl|internal|ccall|void|songPath:string|Play audio file from VFS path"
    "destruct|internal|direct|void||Tear down projectM engine"
    "get_projectm_handle|internal|direct|number||Opaque projectM handle pointer"
    "init|public|direct|number||Initialize EGL/WebGL and projectM, returns 0 on success"
    "set_canvas_selectors|public|ccall|void|primary:string,secondary:string|Set primary/secondary canvas CSS selectors (default #mcanvas/#scanvas)"
    "init_with_canvases|public|ccall|number|primary:string,secondary:string|Set canvas selectors then init (returns 0 on success)"
    "rebind_canvases|public|ccall|number|primary:string,secondary:string|Tear down and re-init against new canvas selectors (single-instance)"
    "load_preset_file|public|ccall|void|vfsPath:string|Load preset from Emscripten VFS path"
    "switch_preset|public|direct|void||Advance playlist to next preset"
    "set_aspect_correction|public|direct|void|enabled:boolean|Enable bezel/aspect correction"
    "render_frame|public|direct|void||Render one visualization frame"
    "start_render|public|direct|void|width:number,height:number|Create render targets and start loop"
    "set_window_size|public|direct|void|width:number,height:number|Resize projectM viewport"
    "set_mesh|public|direct|void|width:number,height:number|Set per-pixel mesh grid size"
    "add_preset_path|internal|direct|void||Register default /presets/ playlist directory"
    "add_existing_vfs_presets|internal|direct|void||Bulk-add numbered presets from VFS"
    "add_preset_file|public|ccall|void|vfsPath:string|Add preset file to playlist"
    "add_custom_milk_paths|internal|direct|void|count:number|Add custom_milk_fixed presets by count"
    "projectm_pcm_add_float_wrapper|public|direct|void|pmHandle:number,audioPtr:pointer,samplesPerChannel:number,channels:number|Feed interleaved float PCM (use feedPcmFloat helper)"
    "pcm_ring_init|public|direct|number|capacityFrames:number|Allocate the WASM-owned PCM ring (0 = default 16384 frames), returns 1 on success"
    "pcm_ring_shutdown|internal|direct|void||Release the PCM ring"
    "pcm_ring_drain|internal|direct|number||Feed every frame written since the last drain, returns frames fed"
    "get_pcm_ring_header_ptr|public|direct|number||Byte offset of the ring's int32 header in the WASM heap"
    "get_pcm_ring_data_ptr|public|direct|number||Byte offset of the ring's interleaved float storage in the WASM heap"
    "get_pcm_ring_capacity_frames|public|direct|number||Ring capacity in stereo frames"
    "get_pcm_ring_index_modulus|public|direct|number||Modulus the ring's frame indices wrap at"
    "get_pcm_ring_write_index|internal|direct|number||Current producer write index, in frames"
    "get_pcm_ring_read_index|internal|direct|number||Current drain read index, in frames"
    "get_pcm_ring_overruns|internal|direct|number||Drains that skipped unread audio because producers lapped the ring"
    "attach_worklet_ingest|public|direct|void||Hand the audio worklet its ring descriptor and install the postMessage fallback"
    "connect_media_element_source|public|ccall|number|selector:string|Route an <audio>/<video> element into the worklet (returns 1 on success)"
    "create_sprite|internal|direct|void||Create demo user sprite"
    "stop_worklet_playback|internal|direct|void||Stop audio worklet playback"
    "set_audio_source_to_stream|internal|direct|void|isStreaming:boolean|Toggle streaming vs capture audio source"
    "set_preset_locked|public|direct|void|locked:boolean|Lock or unlock automatic preset switching"
    "set_transparency_mode|public|direct|void|enabled:boolean|Enable glass-layer transparency on near-black pixels"
    "get_transparency_mode|public|direct|boolean||Whether transparency mode is enabled"
    "set_transparency_threshold|public|direct|void|threshold:number|Set RGB threshold for transparency mode (default 0.01)"
    "get_transparency_threshold|public|direct|number||Current transparency threshold"
    "set_perf_hud|internal|direct|void|enabled:number|Toggle on-canvas performance HUD"
    "set_target_fps|public|direct|void|fps:number|Set render target frame rate"
    "set_quality_governor|public|direct|void|enabled:boolean|Enable adaptive quality governor"
    "get_quality_tier|public|direct|number||Current quality tier index (0=high, 1=regular, 2=low)"
    "get_governor_render_scale|public|direct|number||Current governor internal render-scale factor (1.0/0.75/0.5)"
    "get_governor_blur_cap|public|direct|number||Current governor blur-level cap (-1 = unlimited, else 0-3)"
    "is_preset_ready|internal|direct|number|minFramesSinceReady:number|Whether preset shaders are ready"
    "get_rendered_frame_count|internal|direct|number||Total frames rendered since init"
    "preset_switch_failed|internal|direct|number||Whether last preset switch failed (0/1)"
    "get_omp_enabled|internal|direct|number||Whether OpenMP was compiled in (0/1)"
    "get_omp_max_threads|internal|direct|number||Configured OpenMP max thread count"
    "get_omp_thread_count_in_parallel|internal|direct|number||OpenMP threads observed in parallel region"
    "get_omp_blocktime|internal|direct|number||libomp spin-wait blocktime in ms (0 = sleep immediately, -1 = no libomp)"
    "shader_cache_begin_load|internal|ccall|void|cacheKey:string|Begin preset load with optional transpiled GLSL cache key"
    "shader_cache_import_glsl|internal|ccall|void|shaderType:number,glsl:string|Inject cached transpiled GLSL (0=warp, 1=composite)"
    "shader_cache_end_load|internal|direct|void||Clear transpiled GLSL cache key after preset load"
    "get_glsl_generator_version|public|direct|number||GLSL generator version enum for cache invalidation"
    "pm_handle_context_loss|public|direct|void||Tear down GL state after WebGL context loss"
    "dual_fbo_begin_transition|public|direct|boolean||Allocate preset-B FBO for transition"
    "dual_fbo_end_transition|internal|direct|void||Finalize dual-FBO transition"
    "dual_fbo_cancel_transition|internal|direct|void||Cancel in-progress dual-FBO transition"
    "dual_fbo_swap_preset_a|internal|direct|void||Swap preset A ping-pong buffers"
    "dual_fbo_swap_preset_b|internal|direct|void||Swap preset B ping-pong buffers"
    "dual_fbo_get_a_read_fbo|internal|direct|number||Preset A read FBO handle"
    "dual_fbo_get_a_write_fbo|internal|direct|number||Preset A write FBO handle"
    "dual_fbo_get_a_read_tex|internal|direct|number||Preset A read texture handle"
    "dual_fbo_get_a_write_tex|internal|direct|number||Preset A write texture handle"
    "dual_fbo_get_b_read_fbo|internal|direct|number||Preset B read FBO handle"
    "dual_fbo_get_b_write_fbo|internal|direct|number||Preset B write FBO handle"
    "dual_fbo_get_b_read_tex|internal|direct|number||Preset B read texture handle"
    "dual_fbo_get_b_write_tex|internal|direct|number||Preset B write texture handle"
    "dual_fbo_is_preset_a_allocated|public|direct|boolean||Whether preset-A FBO is allocated (lazily allocated per transition)"
    "dual_fbo_is_preset_b_allocated|public|direct|boolean||Whether preset-B FBO is allocated"
    "dual_fbo_set_idle_release_seconds|public|direct|void|seconds:number|Idle seconds before the preset-A FBO pair is reclaimed (0=immediate, <0=never)"
    "dual_fbo_get_idle_release_seconds|public|direct|number||Configured preset-A idle release threshold in seconds"
    "dual_fbo_is_preset_b_ready|public|direct|boolean||Whether preset-B shaders are ready"
    "dual_fbo_get_format|public|direct|number||FBO format index (0=RGBA32F, 1=RGBA16F, 2=RGBA8)"
    "dual_fbo_render_preset_a|internal|direct|void||Render preset A into dual FBO"
    "dual_fbo_render_preset_b|internal|direct|void||Render preset B into dual FBO"
    "transition_start|public|direct|void||Start visual preset transition blend"
    "transition_cancel|public|direct|void||Cancel active transition"
    "transition_is_active|public|direct|boolean||Whether a transition is in progress"
    "transition_get_blend|public|direct|number||Current transition blend factor 0..1"
    "transition_set_duration|public|direct|void|seconds:number|Set transition duration in seconds"
    "transition_get_duration|public|direct|number||Configured transition duration in seconds"
    "set_deterministic_seed|public|direct|void|enabled:boolean,seed:number|Pin libprojectM's RNG to a seed so a preset renders identical pixels run to run"
    "is_deterministic_seed|public|direct|boolean||Whether deterministic RNG seeding is active"
    "set_deterministic_clock|public|direct|void|enabled:boolean,fps:number|Drive the engine from a virtual clock where frame N happens at N/fps (golden-image capture only, never perf runs)"
    "is_deterministic_clock|public|direct|boolean||Whether the virtual clock is active"
    "deterministic_now_ms|public|direct|number||The host time base in milliseconds: virtual when the clock is on, real otherwise"
    "deterministic_frame_index|public|direct|number||Frames ticked since the virtual clock was last enabled"
    "set_render_loop_paused|public|direct|void|paused:boolean|Pause/resume the requestAnimationFrame main loop so a harness can drive render_frame() itself"
)
